[versions]
opentelemetry = "1.30.1-alpha"
mockito = "5.5.0"
junit = "5.10.0"

[libraries]
opentelemetry-platform = { module = "io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha", version.ref = "opentelemetry" }
androidx-appcompat = "androidx.appcompat:appcompat:1.6.1"
androidx-navigation-fragment = "androidx.navigation:navigation-fragment:2.7.4"
androidx-core = "androidx.core:core:1.12.0"

#Testing
opentelemetry-sdk-testing = { module = "io.opentelemetry:opentelemetry-sdk-testing", version.ref = "opentelemetry" }
androidx-test-core = "androidx.test:core:1.5.0"
androidx-test-runner = "androidx.test:runner:1.5.2"
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit" }
robolectric = "org.robolectric:robolectric:4.10.3"
assertj-core = "org.assertj:assertj-core:3.24.2"
awaitility = "org.awaitility:awaitility:4.2.0"

#Compilation
desugarJdkLibs = "com.android.tools:desugar_jdk_libs:2.0.3"
nullaway = "com.uber.nullaway:nullaway:0.10.14"
errorprone-core = "com.google.errorprone:error_prone_core:2.22.0"
errorprone-javac = "com.google.errorprone:javac:9+181-r4173-1"
findbugs-jsr305 = "com.google.code.findbugs:jsr305:3.0.2"
spotless-plugin = "com.diffplug.spotless:spotless-plugin-gradle:6.22.0"
errorprone-plugin = "net.ltgt.gradle:gradle-errorprone-plugin:3.1.0"
nullaway-plugin = "net.ltgt.gradle:gradle-nullaway-plugin:1.6.0"
animalsniffer-plugin = "ru.vyarus:gradle-animalsniffer-plugin:1.7.1"
androd-plugin = "com.android.tools.build:gradle:8.1.2"

[bundles]
mockito = ["mockito-core", "mockito-junit-jupiter"]
junit = ["junit-jupiter-api", "junit-jupiter-engine", "junit-vintage-engine"]

[plugins]
