name: Build

on:
  push:
    branches:
      - main
      - release/*
  workflow_dispatch:

jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK for running Gradle
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17.0.6
        # TODO: Build and publish a snapshot instead!
      - name: run gradle
        run: ./gradlew check

  workflow-notification:
    needs:
      - build
    if: always()
    uses: ./.github/workflows/reusable-workflow-notification.yml
    with:
      success: ${{ needs.build.result == 'success' }}