name: Build

on:
  push:
    branches:
      - main
      - release/*
  workflow_dispatch:

jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK for running Gradle
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17.0.6
      - name: run gradle check
        run: ./gradlew check
      - name: publish snapshot
        # final=false here means SNAPSHOT
        run: ./gradlew publishMavenPublicationToSonatypeRepository -Prelease=true -Pfinal=false
        env:
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_KEY: ${{ secrets.SONATYPE_KEY }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}

  markdown-link-check:
    # release branches are excluded to avoid unnecessary maintenance
    if: ${{ !startsWith(github.ref_name, 'release/') }}
    uses: ./.github/workflows/reusable-markdown-link-check.yml

  workflow-notification:
    needs:
      - build
    if: failure() && github.run_attempt == 1
    uses: ./.github/workflows/reusable-workflow-notification.yml
    with:
      success: ${{ needs.build.result == 'success' }}